# -*- coding: utf-8 -*-
"""OTP_generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WiRQMhuliq3w-_XtQ5vXarm8eSVfobg3

# One Time Password Generator
"""

#import libraries
import math,random

#OTP generator function 
def OTP_gen():
  digits = "0123456789"
  OTP = ""

  #range of 5 char, random numbers between 0 to 9
  #math.floor -> nearest int number
  for i in range(5):
    OTP += digits[math.floor(random.random()*10)]   
  
  return OTP

#print the result
print("OTP of 5 digits is: ",OTP_gen())